#define SIMULATOR_SCREEN_I4		0
#define SIMULATOR_SCREEN_I5		1
#define SIMULATOR_SCREEN_I6		2
#define SIMULATOR_SCREEN_IPAD	3


#if defined MAC_OS
	#define SIMULATOR_SCREEN	SIMULATOR_SCREEN_I6
	#define SIMULATOR_VERSION	VERSION_750x1334
#elif defined ANDROID_OS
	#define SIMULATOR_SCREEN	SIMULATOR_SCREEN_I6
	#define SIMULATOR_VERSION	VERSION_750x1334
#else
#define SIMULATOR_SCREEN	SIMULATOR_SCREEN_I6
#if defined _WINDOWS
#define SIMULATOR_VERSION  VERSION_750x1334
#else
#if defined(VERSION_480x800)
#define SIMULATOR_VERSION  VERSION_480x800
#else
#define SIMULATOR_VERSION 0
#endif
#endif
#endif

#define SIMULATOR_SCREEN_SCALE		0.5f

//iphone 4
#if (SIMULATOR_SCREEN == SIMULATOR_SCREEN_I4)
#define SIMULATOR_SCREEN_WIDTH 540
#define SIMULATOR_SCREEN_HEIGHT 960
#define SIMULATOR_RESOURCE_PATH "../res"

//ipadd
#elif (SIMULATOR_SCREEN == SIMULATOR_SCREEN_IPAD)
#define SIMULATOR_SCREEN_WIDTH 768.0f
#define SIMULATOR_SCREEN_HEIGHT 1024.0f
#define SIMULATOR_RESOURCE_PATH "../res"

//i5
#elif (SIMULATOR_SCREEN == SIMULATOR_SCREEN_I5)
#define SIMULATOR_SCREEN_WIDTH 640.0f
#define SIMULATOR_SCREEN_HEIGHT 1136.0f
#define SIMULATOR_RESOURCE_PATH "../res"

//i6
#elif (SIMULATOR_SCREEN == SIMULATOR_SCREEN_I6)
#define SIMULATOR_SCREEN_WIDTH 750.0f
#define SIMULATOR_SCREEN_HEIGHT 1334.0f
#define SIMULATOR_RESOURCE_PATH "../res"

#else
#define SIMULATOR_SCREEN_WIDTH 480.0f
#define SIMULATOR_SCREEN_HEIGHT 800.0f
#define SIMULATOR_RESOURCE_PATH "../res"
#endif

#define SIMULATOR_SUPPORTED_FACEBOOK			false
#define SIMULATOR_SUPPORTED_APPLE_GAMECENTER	true