/**
* File was generated by animation packager.
*/
#ifndef		_HUD_RATEUS_I6_H
#define		_HUD_RATEUS_I6_H


#define		HUD_RATEUS_I6_NUM_MODULES				7
#define		HUD_RATEUS_I6_MODULE_TITLE				0
#define		HUD_RATEUS_I6_MODULE_TEXT				1
#define		HUD_RATEUS_I6_MODULE_TEXT				2
#define		HUD_RATEUS_I6_MODULE_LATER				3
#define		HUD_RATEUS_I6_MODULE_RATE				4
#define		HUD_RATEUS_I6_MODULE_STAR				5


#define		HUD_RATEUS_I6_NUM_FRAMES				9
#define		HUD_RATEUS_I6_FRAME_TITLE				0
#define		HUD_RATEUS_I6_FRAME_TEXT				1
#define		HUD_RATEUS_I6_FRAME_RATE				2
#define		HUD_RATEUS_I6_FRAME_RATE				3
#define		HUD_RATEUS_I6_FRAME_LATER				4
#define		HUD_RATEUS_I6_FRAME_LATER				5


#define		HUD_RATEUS_I6_NUM_ANIMS				8
#define		HUD_RATEUS_I6_ANIM_RATE				0
#define		HUD_RATEUS_I6_ANIM_LATER				4


#endif