/**
* File was generated by animation packager.
*/
#ifndef		_HUD_TOPEBOX_ADS_I6_H
#define		_HUD_TOPEBOX_ADS_I6_H


#define		HUD_TOPEBOX_ADS_I6_NUM_MODULES				1


#define		HUD_TOPEBOX_ADS_I6_NUM_FRAMES				2
#define		HUD_TOPEBOX_ADS_I6_FRAME_SELECT				1


#define		HUD_TOPEBOX_ADS_I6_NUM_ANIMS				4


#endif