/**
* File was generated by animation packager.
*/
#ifndef		_HUD_SHARE_I6_H
#define		_HUD_SHARE_I6_H


#define		HUD_SHARE_I6_NUM_MODULES				4
#define		HUD_SHARE_I6_MODULE_MYSCORE				0
#define		HUD_SHARE_I6_MODULE_QR				1
#define		HUD_SHARE_I6_MODULE_SHADE				2
#define		HUD_SHARE_I6_MODULE_LESS				3


#define		HUD_SHARE_I6_NUM_FRAMES				2
#define		HUD_SHARE_I6_FRAME_LOGO				0
#define		HUD_SHARE_I6_FRAME_LESS				1


#define		HUD_SHARE_I6_NUM_ANIMS				0


#endif