/**
* File was generated by animation packager.
*/
#ifndef		_OBJECT_BG_I6_H
#define		_OBJECT_BG_I6_H


#define		OBJECT_BG_I6_NUM_MODULES				4
#define		OBJECT_BG_I6_MODULE_LOGO				0
#define		OBJECT_BG_I6_MODULE_LOGO				1
#define		OBJECT_BG_I6_MODULE_LOGO				2
#define		OBJECT_BG_I6_MODULE_LOGO				3


#define		OBJECT_BG_I6_NUM_FRAMES				1


#define		OBJECT_BG_I6_NUM_ANIMS				0


#endif